name: oi2
dependencies:
- numpy=1.12
- pandas=0.21
- scikit-learn=0.19
- networkx=2.1
- jinja2=2.9
- python-louvain=0.11
- scipy=1.1
- python=3.6
- pip=21.0
- pip:
  - pcst_fast==1.0.6
  - goenrich==1.7.0
  - axial==0.0.4
